POST http://localhost:3000/api/create_table2 HTTP/1.1
content-type: application/json

{
  "division": "Engineering",
  "layerName": "Roads",
  "layerType": "LINESTRING",
  "columns": [
    {
      "name": "road_name",
      "type": "TEXT",
      "description": "Name of the road"
    },
    {
      "name": "length",
      "type": "FLOAT",
      "description": "Length of the road in kilometers"
    }
  ]
}

### get test table
POST http://localhost:3000/api/load_layer_by_id HTTP/1.1

### delete test table
DELETE http://localhost/api/layer_delete.php HTTP/1.1
content-type: application/json

{
    "formid": "fid_1698768482"
}

### get one
POST http://localhost/api/layer_read_one.php HTTP/1.1
content-type: application/json

{
    "formid": "fid_1698771850"
}

### get telegram update
GET https://api.telegram.org/bot8026922828:AAG6KjaG34BBlvCMFEorEkAgL5FWoqaHMJw/getUpdates


###
POST https://api.telegram.org/bot8026922828:AAG6KjaG34BBlvCMFEorEkAgL5FWoqaHMJw/sendMessage
content-type: application/json

{
    "chat_id": "-4641885288",
    "text": "ทดสอบส่งข้อความกลุ่มครับ 111"
}

###
POST https://api.telegram.org/bot8026922828:AAG6KjaG34BBlvCMFEorEkAgL5FWoqaHMJw/sendMessage
content-type: application/json

{
    "chat_id": "-4641885288",
    "text": "ทดสอบส่งข้อความกลุ่มครับ 111"
}

### MJ token  7039167221:AAHCDu4rRiKZZUbRHD4RtiZarEc1C-oF2iI
POST https://api.telegram.org/bot7039167221:AAHCDu4rRiKZZUbRHD4RtiZarEc1C-oF2iI/sendMessage
content-type: application/json

{
    "chat_id": "-1002284534685",
    "text": "ทดสอบส่งข้อความกลุ่มครับ MJ ทดสอบ"
}

### get update
GET https://api.telegram.org/bot8026922828:AAG6KjaG34BBlvCMFEorEkAgL5FWoqaHMJw/getUpdates



###
GET https://api.telegram.org/bot7039167221:AAHCDu4rRiKZZUbRHD4RtiZarEc1C-oF2iI/getUpdates

###
POST http://localhost:3000/api/v2/load_layer
Content-Type: application/json

{
    "formid": "fid_1724646615775"
}


### sribeuban token 7613191932:AAGv9bQPR-tYeQfYwLygY6f0dqoYxD5i-08
GET  https://api.telegram.org/bot7613191932:AAGv9bQPR-tYeQfYwLygY6f0dqoYxD5i-08/getUpdates

### 
POST https://api.telegram.org/bot7613191932:AAGv9bQPR-tYeQfYwLygY6f0dqoYxD5i-08/sendMessage
content-type: application/json

{
    "chat_id": "-4727728563",
    "text": "ทดสอบส่งข้อความกลุ่มครับ Sribeuban ทดสอบ 3"
}

###
GET https://api.telegram.org/bot7666509037:AAFO4sjV1qQYXAXAzzGALbtsV3qFdrnexkg/getUpdates

### 
POST https://api.telegram.org/bot7666509037:AAFO4sjV1qQYXAXAzzGALbtsV3qFdrnexkg/sendMessage
content-type: application/json

{
    "chat_id": "-4755002640",
    "text": "ทดสอบส่งข้อความกลุ่มครับ Sribeuban ทดสอบ 3"
}


###
GET http://localhost:3000/api/v2/info