POST http://localhost:3000/api/create_table2 HTTP/1.1
content-type: application/json

{
  "division": "Engineering",
  "layerName": "Roads",
  "layerType": "LINESTRING",
  "columns": [
    {
      "name": "road_name",
      "type": "TEXT",
      "description": "Name of the road"
    },
    {
      "name": "length",
      "type": "FLOAT",
      "description": "Length of the road in kilometers"
    }
  ]
}

### get test table
POST http://localhost:3000/api/load_layer_by_id HTTP/1.1

### delete test table
DELETE http://localhost/api/layer_delete.php HTTP/1.1
content-type: application/json

{
    "formid": "fid_1698768482"
}

### get one
POST http://localhost/api/layer_read_one.php HTTP/1.1
content-type: application/json

{
    "formid": "fid_1698771850"
}