version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: geodb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '8080:80'
    networks:
      - app-network
  nodejs:
    image: node:latest
    restart: always
    working_dir: /app/nodejs
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - TZ=Asia/Bangkok
    volumes:
      - ./nodejs:/app/nodejs
    ports:
      - 3000:3000
    command:
      - bash -c "npm i && npm i -g nodemon && nodemon server.js"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql:
